### ISSUE TITLE
Build should report errors.

### ISSUE THREAD

**Issue by fluxsauce** [aquifer/aquifer-git#1]
``` js
            if (error) {
              reject();
            }
```

Really should be

``` js
            if (error) {
              Aquifer.console.log(error, 'error');
              reject();
            }
```

**Comment by chasingmaxwell** [comment]
@fluxsauce I've fixed this by rejecting with the error `reject(error)` and then returning it in the callback to aquifer's extension command API. https://github.com/aquifer/aquifer-git/blob/master/bin/index.js#L281
