### ISSUE TITLE
Running aquifer deploy-git never completes

### ISSUE THREAD

**Issue by mralexho** [aquifer/aquifer-git#10]
Hello,

First, thank you for putting this project together. 

I just built a regular aquifer project and added the aquifer-git extension. When I execute the following command, the node process doesn't seem to ever end (I've let it run for about 20 minutes).

```
$ aquifer deploy-git -r git@bitbucket.org:username/repo.git -b master -m 'initial commit'
Cloning the repository into aquifer-git-N6gjG63.
```

Do you have any ideas?

**Comment by mralexho** [comment]
Running on OS X El Capitan (10.11).

```
$ node -v
v0.12.0

$ drush --version
 Drush Version   :  7.0.0
```

**Comment by chasingmaxwell** [comment]
@mralexho thanks for giving aquifer-git a spin! I wonder if you're having an access permission problem for the repo you're trying to clone. Can you confirm that you're able to clone it normally outside of aquifer?

**Comment by mralexho** [comment]
Yes, I can clone outside of aquifer. Are there any additional details I can include that might be helpful?

**Comment by chasingmaxwell** [comment]
Okay. Could you post your aquifer.json file with the sensitive bits removed?

Some things to try:
1. Update node to at least 0.12.7.
2. Reinstall your extensions: `rm -rf .aquifer && aquifer extensions-load`

nodegit is a little temperamental so I suspect there's an issue between your environment and the nodegit module which aquifer-git depends on.

**Comment by mralexho** [comment]
Sorry I was away on vacation and haven't responded. Here's my aquifer.json file -

```
$ cat aquifer.json
{
  "name": "drupal7",
  "paths": {
    "make": "drupal.make.yml",
    "lock": false,
    "settings": "settings",
    "build": "build",
    "root": "root",
    "themes": {
      "root": "themes",
      "contrib": "themes/contrib",
      "custom": "themes/custom"
    },
    "modules": {
      "root": "modules",
      "contrib": "modules/contrib",
      "custom": "modules/custom",
      "features": "modules/features"
    },
    "files": {
      "root": "files"
    }
  },
  "extensions": {
    "aquifer-coder": {
      "source": "aquifer-coder",
      "eslintrc": "/Users/mralexho/Sites/devel/drupal7/.aquifer/node_modules/aquifer-coder/src/.eslintrc",
      "phpcsStandard": "/Users/mralexho/Sites/devel/drupal7/.aquifer/node_modules/aquifer-coder/vendor/drupalmodule/coder/coder_sniffer/Drupal"
    },
    "aquifer-git": {
      "source": "aquifer-git"
    }
  },
  "refreshCommands": [
    [
      "updb"
    ],
    [
      "cc",
      "all"
    ],
    [
      "en",
      "master"
    ],
    [
      "master-execute",
      "--scope=local"
    ],
    [
      "fra"
    ],
    [
      "rr"
    ]
  ]
}
```

**Comment by mralexho** [comment]
I just updated my node to the latest v4.2.2 LTS. Running the same command threw a new error -

```
$ aquifer deploy-git -r git@bitbucket.org:username/repo.git -b master -m 'initial commit'
/Users/mralexho/Sites/devel/drupal7/.aquifer/node_modules/aquifer-git/node_modules/nodegit/lib/nodegit.js:13
    throw ex;
    ^

Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/mralexho/Sites/devel/drupal7/.aquifer/node_modules/aquifer-git/node_modules/nodegit/lib/nodegit.js:8:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

**Comment by mralexho** [comment]
Okay, reinstalling node fixed the error above. I'm back to the original issue with deploy-git sleeping.

```
$ node -v
v4.2.2

$ npm -v
2.14.7
```

**Comment by chasingmaxwell** [comment]
@mralexho, sorry for the late response. Along with reinstalling node have you also removed your `.aquifer` directory and re-run `aquifer extensions-load`?

**Comment by mralexho** [comment]
Not a problem. Yes, I removed the `.aquifer` directory and ran `aquifer extensions-load` again. I may just go with a different deployment route. Thanks.

**Comment by chasingmaxwell** [comment]
@mralexho thanks for your patience. I've tried to reproduce your issue without success. I'm going to work on adding a verbose flag to the deploy-git command to make it easier to debug issues like this. Maybe you'd be willing to give this another shot after I've done that so I can get to the bottom of the issue you're having?

**Comment by mralexho** [comment]
@chasingmaxwell Gladly!
