### ISSUE TITLE
aquifer-git copies files directory as part of build

### ISSUE THREAD

**Issue by fluxsauce** [aquifer/aquifer-git#12]
Noticed this because I've got a ~25GB files directory and was testing locally. It's ignored in the `.gitignore` so there's no reason to do it in the first place.
- Do not copy `aquifer.json` `"paths"` `"files"`

As I understand this, `aquifer` itself also needs to be adjusted.

**Comment by chasingmaxwell** [comment]
https://github.com/aquifer/aquifer-git/pull/13 should fix this.

**Comment by chasingmaxwell** [comment]
@fluxsauce could you test and confirm?

**Comment by chasingmaxwell** [comment]
#13 was merged
